// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJBZEKMAbz8Ocknv_dIjta6pFncCuBgU',
    appId: '1:958312419373:web:863b3e7eca35f9d96368a4',
    messagingSenderId: '958312419373',
    projectId: 'ug-blood-donate',
    authDomain: 'ug-blood-donate.firebaseapp.com',
    storageBucket: 'ug-blood-donate.appspot.com',
    measurementId: 'G-QNBYFSTZTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXOYbxPajXPiCdCBdMeY2tcDAkaC676I',
    appId: '1:958312419373:android:ff65ab84c7d21c116368a4',
    messagingSenderId: '958312419373',
    projectId: 'ug-blood-donate',
    storageBucket: 'ug-blood-donate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwD0mDYFK00o2X73NsaFk0sZRgAkm_fSE',
    appId: '1:958312419373:ios:76e47370225fdcea6368a4',
    messagingSenderId: '958312419373',
    projectId: 'ug-blood-donate',
    storageBucket: 'ug-blood-donate.appspot.com',
    iosClientId: '958312419373-krmd5log50ljc8oogq9n31u1u9iudhmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ugBloodDonate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwD0mDYFK00o2X73NsaFk0sZRgAkm_fSE',
    appId: '1:958312419373:ios:76e47370225fdcea6368a4',
    messagingSenderId: '958312419373',
    projectId: 'ug-blood-donate',
    storageBucket: 'ug-blood-donate.appspot.com',
    iosClientId: '958312419373-krmd5log50ljc8oogq9n31u1u9iudhmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ugBloodDonate',
  );
}
